app/enablers/__init__.py
from flask import Blueprint

__author__ = 'Manuel Escriche'

enablers = Blueprint('enablers', __name__)

from . import views

app/enablers/views.py
import logging
from flask import Blueprint, render_template, abort, request, redirect, url_for, flash
from flask_login import login_required
from flask_wtf import FlaskForm
from wtforms import SelectField
from kconfig import agileCalendar, enablersBook, enablersBookByName
from kernel.Backlog import BacklogFactory, LocalBacklogFactory
from kernel.Reporter import EnablerReporter
from kernel.Analyser import EnablersAnalyser
from kernel.DataBoard import Data
from kernel.NM_Aggregates import EnablerDeck
from kernel.NM_HelpDeskReporter import DeckReporter

from . import enablers

__author__ = "Manuel Escriche <mev@tid.es>"


class SelectForm(FlaskForm):
    select = SelectField(u'Enabler')


@enablers.route("/", methods=['GET', 'POST'])
@enablers.route("/overview", methods=['GET', 'POST'])
@login_required
def overview():
    form = SelectForm()
    options = [(n, item) for n, item in enumerate(enablersBookByName)]

    if request.method == 'POST':
        enablername = dict(options)[int(form.select.data)]
        return redirect(url_for('enablers.backlog', enablername=enablername))

    form.select.choices = [(n, '{} - {} - {} ({})'
                            .format(n+1, enablersBookByName[item].chapter, item, enablersBookByName[item].mode))
                           for n, item in enumerate(enablersBookByName)]

    analyser = EnablersAnalyser.fromFile()
    analyser.enablersBook = enablersBook
    return render_template('enablers/overview.html', analyser=analyser, calendar=agileCalendar, form=form)


@enablers.route("/backlog/<enablername>", methods=['GET', 'POST'])
@login_required
def backlog(enablername):
    enabler = enablersBook[enablername]
    form = SelectForm()

    options = [(n, item) for n, item in enumerate(enablersBookByName)]

    if request.method == 'POST':
        enablername = dict(options)[int(form.select.data)]
        return redirect(url_for('enablers.backlog', enablername=enablername))

    form.select.choices = [(n, '{} - {} - {} ({})'
                            .format(n+1, enablersBookByName[item].chapter, item, enablersBookByName[item].mode))
                           for n, item in enumerate(enablersBookByName)]

    try:
        backlog_factory = BacklogFactory.getInstance()
        my_backlog = backlog_factory.getEnablerBacklog(enablername)
    except Exception as e:
        logging.warning(e)
        local_factory = LocalBacklogFactory.getInstance()
        my_backlog = local_factory.getEnablerBacklog(enablername)
        flash('Data from local storage obtained at {}'.format(my_backlog.timestamp))

    sortedby = request.args.get('sortedby') if request.args.get('sortedby') else 'name'
    my_backlog.sort(key=my_backlog.sortDict[sortedby])
    reporter = EnablerReporter(enablername, my_backlog)

    return render_template('enablers/backlog.html',
                           enabler=enabler,
                           reporter=reporter,
                           calendar=agileCalendar,
                           form=form)


@enablers.route("/backlog/<enablername>/raw")
@login_required
def raw(enablername):
    enabler = enablersBook[enablername]

    try:
        backlog_factory = BacklogFactory.getInstance()
        my_backlog = backlog_factory.getEnablerBacklog(enablername)
    except Exception as e:
        logging.warning(e)
        local_factory = LocalBacklogFactory.getInstance()
        my_backlog = local_factory.getEnablerBacklog(enablername)
        flash('Data from local storage obtained at {}'.format(my_backlog.timestamp))

    sortedby = request.args.get('sortedby') if request.args.get('sortedby') else 'name'

    my_backlog.sort(key=my_backlog.sortDict[sortedby])
    reporter = EnablerReporter(enablername, my_backlog)

    return render_template('enablers/raw.html',
                           enabler=enabler,
                           reporter=reporter,
                           calendar=agileCalendar)


@enablers.route("/backlog/<enablername>/review")
@login_required
def review(enablername):
    enabler = enablersBook[enablername]

    try:
        backlog_factory = BacklogFactory.getInstance()
        my_backlog = backlog_factory.getEnablerBacklog(enablername)
    except Exception as e:
        logging.warning(e)
        local_factory = LocalBacklogFactory.getInstance()
        my_backlog = local_factory.getEnablerBacklog(enablername)
        flash('Data from local storage obtained at {}'.format(my_backlog.timestamp))

    sortedby = request.args.get('sortedby') if request.args.get('sortedby') else 'name'
    my_backlog.sort(key=my_backlog.sortDict[sortedby])
    reporter = EnablerReporter(enablername, my_backlog)

    return render_template('enablers/review.html',
                           enabler=enabler,
                           reporter=reporter,
                           calendar=agileCalendar)


@enablers.route("/helpdesk/<enablername>", methods=['GET', 'POST'])
@login_required
def helpdesk(enablername):
    enabler = enablersBook[enablername]
    form = SelectForm()
    options = [(n, item) for n, item in enumerate(enablersBookByName)]

    if request.method == 'POST':
        enablername = dict(options)[int(form.select.data)]
        return redirect(url_for('enablers.helpdesk', enablername=enablername))

    form.select.choices = [(n, '{} - {} - {} ({})'
                            .format(n+1, enablersBookByName[item].chapter, item, enablersBookByName[item].mode))
                           for n, item in enumerate(enablersBookByName)]

    deck = EnablerDeck(enabler, *Data.getEnablerHelpDesk(enablername))

    if deck.source == 'store':
        flash('Data from local storage obtained at {}'.format(deck.timestamp))

    sortedby = request.args.get('sortedby') if request.args.get('sortedby') else 'age'

    reporter = DeckReporter(enabler.chapter, deck)

    return render_template('enablers/helpdesk.html',
                           enabler=enabler,
                           sortedby=sortedby,
                           data=deck,
                           reporter=reporter,
                           form=form,
                           calendar=agileCalendar)


@enablers.route("/<enablername>/publish")
@login_required
def publish(enablername):
    pass


@enablers.route("/<enablername>/packages")
@login_required
def packages(enablername):
    pass


@enablers.route("/<enablername>/deploy")
@login_required
def deploy(enablername):
    pass

app/helpdesk/__init__.py
from flask import Blueprint

__author__ = 'Manuel Escriche'

helpdesk = Blueprint('helpdesk', __name__)

from . import views

app/helpdesk/views.py
__author__ = "Manuel Escriche <mev@tid.es>"
import time
from operator import attrgetter
from flask import Blueprint, render_template, abort, request, redirect, url_for, flash
from flask_login import login_required
from flask_wtf import FlaskForm
from wtforms import SelectField

from kconfig import agileCalendar, helpdeskBookByName
from kernel.DataBoard import Data
from kernel.NM_Aggregates import Deck, iDeck, DeskDeck, DeskiDeck, ChannelDeck, InnChannel
from kernel.NM_HelpDeskReporter import ChannelReporter, DeskReporter

from . import helpdesk

class SelectForm(FlaskForm):
    select = SelectField(u'Channels')


@helpdesk.route("/", methods=['GET', 'POST'])
@login_required
def overview():
    refresh = request.args.get('refresh') if request.args.get('refresh') else False
    maindesk = helpdeskBookByName['Main-Help-Desk']
    coachdesk = helpdeskBookByName['Coaches-Help-Desk']

    if refresh:
        deskdata = DeskDeck(maindesk, *Data.getDesk(maindesk))
        maindeskreporter = DeskReporter(maindesk, deskdata)
        coachdata = DeskDeck(coachdesk, *Data.getDesk(coachdesk))
        coachdeskreporter = DeskReporter(coachdesk, coachdata)
    else:
        maindeskreporter = DeskReporter.fromFile(maindesk)
        coachdeskreporter = DeskReporter.fromFile(coachdesk)

    return render_template('helpdesk/overview.html',
                           maindesk = maindesk,
                           mainreporter = maindeskreporter,
                           coachdesk = coachdesk,
                           coachreporter = coachdeskreporter,
                           calendar = agileCalendar)


@helpdesk.route("/main", methods=['GET', 'POST'])
@login_required
def main():
    refresh = request.args.get('refresh') if request.args.get('refresh') else False
    desk = helpdeskBookByName['Main-Help-Desk']
    form = SelectForm()
    options = [(n,item) for n,item in enumerate(desk.channels)]
    if request.method == 'POST':
        channelname = dict(options)[int(form.select.data)]
        return redirect(url_for('helpdesk.channel', channelname=channelname))
    form.select.choices = options

    if refresh:
        data = Deck(*Data.getFocusedDesk(desk))
        if data.source == 'store':
            flash('Unable to get fresh data from JIRA server')
        else:
            reporter = DeskReporter(desk, data)
    else:
        data = Deck(*Data.getDesk(desk))
        if data.source == 'store':
            flash('Data from local storage obtained at {}'.format(data.timestamp))

    reporter = DeskReporter.fromFile(desk)

    return render_template('helpdesk/maindesk.html',
                           desk=desk,
                           data=data,
                           reporter=reporter,
                           form=form,
                           calendar=agileCalendar)


@helpdesk.route("/channel/<channelname>", methods=['GET', 'POST'])
@login_required
def channel(channelname):
    refresh = request.args.get('refresh') if request.args.get('refresh') else False
    deskname = 'Main-Help-Desk'
    form = SelectForm()
    options = [(n,item) for n,item in enumerate(helpdeskBookByName[deskname].channels)]
    if request.method == 'POST':
        channelname = dict(options)[int(form.select.data)]
        return redirect(url_for('.channel', channelname=channelname))
    form.select.choices = options

    channel = helpdeskBookByName[deskname].channels[channelname]
    channeldata = ChannelDeck(channel, *Data.getChannel(channel.key))

    if channeldata.source == 'store':
        flash('Data from local storage obtained at {}'.format(channeldata.timestamp))

    if refresh:
        if channeldata.source == 'store':
            flash('Unable to get fresh data from JIRA server')
            reporter = ChannelReporter.fromFile(channel)
        else:
            reporter = ChannelReporter(channel, channeldata)
    else:
        reporter = ChannelReporter.fromFile(channel)

    return render_template('helpdesk/maindeskchannel.html',
                           book = helpdeskBookByName, helpdeskname = deskname, channelname=channelname,
                           data = channeldata,
                           reporter = reporter,
                           form = form,
                           calendar=agileCalendar)

@helpdesk.route("/lab")
#@login_required
def lab():
    deskname = 'Main-Help-Desk'
    channelname = 'Lab'
    channel = helpdeskBookByName[deskname].channels[channelname]
    channeldata = ChannelDeck(channel, *Data.getChannel(channel.key))
    if channeldata.source == 'store':
        flash('Data from local storage obtained at {}'.format(channeldata.timestamp))
    reporter = ChannelReporter.fromFile(channel)
    return render_template('helpdesk/pchannel.html',
                           book = helpdeskBookByName, helpdeskname = deskname, channelname=channelname,
                           data = channeldata,
                           reporter = reporter,
                           calendar=agileCalendar)

@helpdesk.route("/tech")
#@login_required
def tech():
    deskname = 'Main-Help-Desk'
    channelname = 'Tech'
    channel = helpdeskBookByName[deskname].channels[channelname]
    channeldata = ChannelDeck(channel, *Data.getChannel(channel.key))
    if channeldata.source == 'store':
        flash('Data from local storage obtained at {}'.format(channeldata.timestamp))
    reporter = ChannelReporter.fromFile(channel)

    return render_template('helpdesk/pchannel.html',
                           book = helpdeskBookByName, helpdeskname = deskname, channelname=channelname,
                           data = channeldata,
                           reporter = reporter,
                           calendar=agileCalendar)

@helpdesk.route("/coaches", methods=['GET', 'POST'])
@login_required
def coaches():
    refresh = request.args.get('refresh') if request.args.get('refresh') else False
    desk = helpdeskBookByName['Coaches-Help-Desk']

    form = SelectForm()
    options = [(n,item) for n,item in enumerate(desk.channels)]
    if request.method == 'POST':
        channelname = dict(options)[int(form.select.data)]
        return redirect(url_for('.cchannel', channelname=channelname))
    form.select.choices = options

    if refresh:
        data = Deck(*Data.getFocusedDesk(desk))
        if data.source == 'store':
            flash('Unable to get fresh data from JIRA server')
        else:
            reporter = DeskReporter(desk, data)
    else:
        data = Deck(*Data.getDesk(desk))
        if data.source == 'store':
            flash('Data from local storage obtained at {}'.format(data.timestamp))

    reporter = DeskReporter.fromFile(desk)

    return render_template('helpdesk/coachesdesk.html',
                           desk=desk,
                           form=form,
                           data=data,
                           reporter=reporter,
                           calendar=agileCalendar)

@helpdesk.route("/coaches/channel/<channelname>", methods=['GET', 'POST'])
@login_required
def cchannel(channelname):
    refresh = True if request.args.get('refresh') else False
    deskname = 'Coaches-Help-Desk'
    form = SelectForm()
    options = [(n,item) for n,item in enumerate(helpdeskBookByName[deskname].channels)]
    if request.method == 'POST':
        channelname = dict(options)[int(form.select.data)]
        return redirect(url_for('.cchannel', channelname=channelname))

    form.select.choices = options
    channel = helpdeskBookByName[deskname].channels[channelname]
    channeldata = ChannelDeck(channel, *Data.getChannel(channel.key))

    if channeldata.source == 'store':
        flash('Data from local storage obtained at {}'.format(channeldata.timestamp))

    if refresh:
        if channeldata.source == 'store':
            flash('Unable to get fresh data from JIRA server')
            reporter = ChannelReporter.fromFile(channel)
        else:
            reporter = ChannelReporter(channel, channeldata)
    else:
        reporter = ChannelReporter.fromFile(channel)

    return render_template('helpdesk/coachesdeskchannel.html',
                           book = helpdeskBookByName, helpdeskname = deskname, channelname=channelname,
                           data = channeldata,
                           reporter = reporter, form = form,
                           calendar=agileCalendar)


@helpdesk.route("/tools", methods=['GET', 'POST'])
@login_required
def tools():
    refresh = True if request.args.get('refresh') else False
    desk = helpdeskBookByName['ToolsSupport-Help-Desk']
    form = SelectForm()
    options = [(n,item) for n,item in enumerate(desk.channels)]
    if request.method == 'POST':
        channelname = dict(options)[int(form.select.data)]
        return redirect(url_for('.tchannel', channelname=channelname))
    form.select.choices = options

    if refresh:
        data = iDeck(*Data.getFocusedDesk(desk))
        if data.source == 'store':
            flash('Unable to get fresh data from JIRA server')
        else:
            reporter = DeskReporter(desk, data)
    else:
        data = iDeck(*Data.getDesk(desk))
        if data.source == 'store':
            flash('Data from local storage obtained at {}'.format(data.timestamp))

    reporter = DeskReporter.fromFile(desk)



    return render_template('helpdesk/toolsdesk.html',
                           desk=desk,
                           form=form,
                           data=data,
                           reporter=reporter,
                           calendar=agileCalendar)


@helpdesk.route("/tools/channel/<channelname>", methods=['GET', 'POST'])
@login_required
def tchannel(channelname):
    refresh = True if request.args.get('refresh') else False
    deskname = 'ToolsSupport-Help-Desk'
    form = SelectForm()
    options = [(n,item) for n,item in enumerate(helpdeskBookByName[deskname].channels)]
    if request.method == 'POST':
        channelname = dict(options)[int(form.select.data)]

app/templates/enablers/layout.html
{% extends "layout.html" %}

{% block submenu %}
    <nav  id="menu">
        <ul>
            <li><a href="{{ url_for('.helpdesk', enablername=enabler.name) }}" class="active">Helpdesk</a></li>
            <li><a href="{{ url_for('.backlog', enablername=enabler.name) }}" class="active">Backlog</a></li>
            <li><a href="{{ url_for('.raw', enablername=enabler.name) }}" class="active">Raw</a></li>
            <li><a href="{{ url_for('.review', enablername=enabler.name) }}" class="active">Review</a></li>
        </ul>
    </nav>

{% endblock %}

app/templates/enablers/overview.html
{% extends "layout.html" %}

{% block tool %} Backlog {% endblock %}
{% block header %} Enablers {% endblock %}


{% block content %}
    <p>
        <form method="POST" action="{{ url_for('enablers.overview') }}" align="center">
          Enablers:  {{ form.select}} <input type="submit" value="GO!!" style="width: 80px; height: 40px;" >
        </form>
    </p>
    <section id="overview">

        <table class="enabler_identification">
            <colgroup>
                <col id="concept">
                <col id="value">
            </colgroup>
            <tbody>
                <tr><td class="key"># Enablers </td>   <td class="value">{{ analyser.enablersBook|length }}</td></tr>

                <tr><td class="key">Backlog Composition: </td><td class="value"> {{ analyser.length }} Issues =
                    {{ analyser.issueType['Epic'] }} Epics +
                    {{ analyser.issueType['Feature'] }} Features +
                    {{ analyser.issueType['Story'] }} Stories +
                    {{ analyser.issueType['WorkItem'] }} WorkItems +
                    {{ analyser.issueType['Bug'] }} Bugs
                </td></tr>
                <tr><td class="key">Backlog Time Perspectives</td><td class="value"> {{ analyser.length }} Issues =
                {{ analyser.perspective['Implemented'] }} Implemented +
                <b style="color:red"> {{ analyser.perspective['Working On'] }} Working On </b>+
                {{ analyser.perspective['Foreseen'] }} Foreseen
                </td> </tr>
                <tr><td class="key"><b style="color:red">Sprint Backlog</b> Status: </td>
                <td class="value"> <b style="color:red"> {{ analyser.sprint_status.items()|sum(attribute="1") }}  Issues </b> =
                {% for item in analyser.sprint_status %}
                    {% if loop.first %}
                        {{ analyser.sprint_status[item] }} {{ item }}
                    {% else %}
                        + {{ analyser.sprint_status[item] }} {{ item }}
                    {% endif %}
                {% endfor %}
                </td></tr>
            </tbody>
        </table>

        <table class='backlog_graphs'>
            <colgroup>
                <col class="column">
                <col class="column">
                <col class="column">
            </colgroup>
            <tbody>
            <tr>
            <td id="composition-graph" class="chart">
        <script>
        var chart = new Highcharts.Chart({
            chart: {
                renderTo: 'composition-graph',
                plotBackgroundColor: null,
                plotBorderWidth: 1,
                plotShadow: false
            },
            title: {
                text: 'Tech Backlog Composition'
            },
            tooltip: {
                pointFormat: '<b>{point.y} issues ({point.percentage:.1f}%) share</b>'
            },
            plotOptions: {
                pie: {
                    dataLabels: {
                        enabled: true,
                        format: '<b>{point.name}</b>: <br/> {point.y} ({point.percentage:.1f}%)'
                    }
                }
            },
            series: [{
                type: 'pie',
                name: 'Issue type',
                data: {{ analyser.issueType_graph_data|safe }}
            }]
        });
        </script>
                </td>

            <td id="perspective-graph" class="chart">
        <script>
        var chart = new Highcharts.Chart({
            chart: {
                type: 'column',
                renderTo: 'perspective-graph'
            },
            title: {
                text: 'Tech Backlog Time Perspective'
            },
            xAxis: {
                type: 'category',
                labels: {
                    rotation: -45,
                    fontSize: '13px',
                    fontFamily: 'Verdana, sans-serif'
                }
            },
            yAxis: {
                min: 0,
                title: null
            },
            legend: {
                enabled:false
            },
            tooltip: {
                pointFormat: '<b>{point.y} issues</b>'
            },
            series: [{
                name: 'Time Perspective',
                data: {{ analyser.perspective_graph_data|safe }},
                dataLabels: {
                    enabled: true
                }
            }]
        });
        </script>
            </td>

            <td id="errors-graph" class="chart">
            <script>
            var chart = new Highcharts.Chart({
            chart: {
                renderTo: 'errors-graph',
                plotBackgroundColor: null,
                plotBorderWidth: 1,
                plotShadow: false
            },
            title: {
                text: "Backlog - Issues with Errors"
            },
            tooltip: {
                pointFormat: '<b>{point.y} issues ({point.percentage:.1f}%) share</b>'
            },
            plotOptions: {
                pie: {
                    dataLabels: {
                        enabled: true,
                        format: '<b>{point.name}</b>: <br/> {point.y} ({point.percentage:.1f}%)'
                    }
                }
            },
            series: [{
                type: 'pie',
                name: 'Issue status share',
                data: {{ analyser.errors_graph_data|safe }}
            }]
            });
            </script>
            </td>

            </tr>
            <tr>
                <td id="burndown-graph" colspan="2">
                <script>
            var chart = new Highcharts.Chart({

            chart: {
                renderTo: 'burndown-graph',
                plotBackgroundColor: null,
                plotBorderWidth: 1,
                plotShadow: false
            },
            title: {
                text: "Sprint Backlog Evolution"
            },
            legend: {
                layout: 'horizontal',
                align: 'center',
                itemMarginTop: 20,
                verticalAlign: 'top',
                borderWidth: 0
            },
            xAxis: {
                title: {
                  text: "# Day in month"
                },
                categories: {{ analyser.burndown_graph_data.categories|safe }}
            },
            yAxis: {
                title: {
                    text: 'Issues (#)'
                },
                floor: 0
            },
            plotOptions: {
                column: {
                    dataLabels: {
                        enabled: true
                    }
                }
            },
            series: [
                {{ analyser.burndown_graph_data.reference|safe }},
                {{ analyser.burndown_graph_data.actual|safe }},
                {{ analyser.burndown_graph_data.closed|safe }}
            ]
        });
                </script>
            </td>
                <td id="status-graph" class="chart">
        <script>
        var chart = new Highcharts.Chart({
            chart: {
                renderTo: 'status-graph',
                plotBackgroundColor: null,
                plotBorderWidth: 1,
                plotShadow: false
            },
            title: {
                text: "Sprint Backlog Status"
            },
            tooltip: {
                pointFormat: '<b>{point.y} issues ({point.percentage:.1f}%) share</b>'
            },
            plotOptions: {
                pie: {
                    dataLabels: {
                        enabled: true,
                        format: '<b>{point.name}</b>: <br/> {point.y} ({point.percentage:.1f}%)'
                    }
                }
            },
            series: [{
                type: 'pie',
                name: 'Issue status',
                data: {{ analyser.sprint_status_graph_data|safe }}
            }]
        });
        </script>
                </td>
            </tr>
              <tr>
             <td id="historic-graph" colspan="3">
                <script>
            var chart = new Highcharts.Chart({

            chart: {
                renderTo: 'historic-graph',
                plotBackgroundColor: null,
                plotBorderWidth: 1,
                plotShadow: false
            },
            title: {
                text: "Enablers Backlog Evolution"
            },
            legend: {
                layout: 'horizontal',
                align: 'center',
                itemMarginTop: 20,
                verticalAlign: 'top',
                borderWidth: 0
            },
            xAxis: {
                title: {
                  text: "#Month"
                },
                categories: {{ analyser.implemented_graph_data.categories|safe }},
                max: {{ analyser.implemented_graph_data.ncategories }}
            },
            yAxis: {
                title: {
                    text: 'Issues (#)'
                },
                floor: 0
            },

            plotOptions: {
                column: {
                    dataLabels: {
                        enabled: true
                    }
                }
            },
            series: [
                {{ analyser.implemented_graph_data.created|safe }},
                {{ analyser.implemented_graph_data.resolved|safe }},
                {{ analyser.implemented_graph_data.updated|safe }},
                {{ analyser.implemented_graph_data.released|safe }},
                {{ analyser.implemented_graph_data.progress|safe }}
            ]
        });
                </script>
            </td>
        </tr>
        </table>

        <table class='enablers_graph'>
            <colgroup>
                <col class="column">
            </colgroup>
            <tbody>
            <tr>
            <td id="enablers-workingOn-graph" class="overview_chart">
            <script>
            var chart = new Highcharts.Chart({
            chart: {
                type: 'bar',
                renderTo: 'enablers-workingOn-graph'
            },
            title: {
                text: "Sprint Backlog Status by Enabler"
            },
            xAxis: {
                categories: {{ analyser.enablers|safe }}
            },
            yAxis: {
                min: 0,
                title: {
                    text: '# Issues'
                },
                stackLabels: {
                    enabled: true,
                    style: {
                        fontWeight: 'bold',
                        color: (Highcharts.theme && Highcharts.theme.textColor) || 'gray'
                    }
                }
            },
            legend: {
                verticalAlign: 'top',
                y: 25
            },
            plotOptions: {
                series: {
                    stacking: 'normal'
                    }
            },
            series: {{ analyser.enablers_sprint_status_graph_data|safe }}
            });
            </script>
            </td>
            </tr>

            <tr>
            <td id="enablers-errors-graph" class="overview_chart">
            <script>
            var chart = new Highcharts.Chart({
            chart: {
                type: 'bar',
                renderTo: 'enablers-errors-graph'
            },
            title: {
                text: "Backlog Errors by Enabler"
            },
            xAxis: {
                categories: {{ analyser.enablers|safe }}
            },
            yAxis: {
                min: 0,
                title: {
                    text: '# Issues'
                },
                stackLabels: {
                    enabled: true,
                    style: {
                        fontWeight: 'bold',
                        color: (Highcharts.theme && Highcharts.theme.textColor) || 'gray'
                    }
                }
            },
            legend: {
                verticalAlign: 'top',
                y: 25
            },
            plotOptions: {
                series: {
                    stacking: 'normal'
                    }
            },
            series: {{ analyser.enablers_errors_graph_data|safe }}
            });
            </script>
            </td>
            </tr>
        </table>

    </section>

{% endblock %}