app/helpdesk/__init__.py
from flask import Blueprint

__author__ = 'Manuel Escriche'

helpdesk = Blueprint('helpdesk', __name__)

from . import views

app/helpdesk/views.py
__author__ = "Manuel Escriche <mev@tid.es>"
import time
from operator import attrgetter
from flask import Blueprint, render_template, abort, request, redirect, url_for, flash
from flask_login import login_required
from flask_wtf import FlaskForm
from wtforms import SelectField

from kconfig import agileCalendar, helpdeskBookByName
from kernel.DataBoard import Data
from kernel.NM_Aggregates import Deck, iDeck, DeskDeck, DeskiDeck, ChannelDeck, InnChannel
from kernel.NM_HelpDeskReporter import ChannelReporter, DeskReporter

from . import helpdesk

class SelectForm(FlaskForm):
    select = SelectField(u'Channels')


@helpdesk.route("/", methods=['GET', 'POST'])
@login_required
def overview():
    refresh = request.args.get('refresh') if request.args.get('refresh') else False
    maindesk = helpdeskBookByName['Main-Help-Desk']
    coachdesk = helpdeskBookByName['Coaches-Help-Desk']

    if refresh:
        deskdata = DeskDeck(maindesk, *Data.getDesk(maindesk))
        maindeskreporter = DeskReporter(maindesk, deskdata)
        coachdata = DeskDeck(coachdesk, *Data.getDesk(coachdesk))
        coachdeskreporter = DeskReporter(coachdesk, coachdata)
    else:
        maindeskreporter = DeskReporter.fromFile(maindesk)
        coachdeskreporter = DeskReporter.fromFile(coachdesk)

    return render_template('helpdesk/overview.html',
                           maindesk = maindesk,
                           mainreporter = maindeskreporter,
                           coachdesk = coachdesk,
                           coachreporter = coachdeskreporter,
                           calendar = agileCalendar)


@helpdesk.route("/main", methods=['GET', 'POST'])
@login_required
def main():
    refresh = request.args.get('refresh') if request.args.get('refresh') else False
    desk = helpdeskBookByName['Main-Help-Desk']
    form = SelectForm()
    options = [(n,item) for n,item in enumerate(desk.channels)]
    if request.method == 'POST':
        channelname = dict(options)[int(form.select.data)]
        return redirect(url_for('helpdesk.channel', channelname=channelname))
    form.select.choices = options

    if refresh:
        data = Deck(*Data.getFocusedDesk(desk))
        if data.source == 'store':
            flash('Unable to get fresh data from JIRA server')
        else:
            reporter = DeskReporter(desk, data)
    else:
        data = Deck(*Data.getDesk(desk))
        if data.source == 'store':
            flash('Data from local storage obtained at {}'.format(data.timestamp))

    reporter = DeskReporter.fromFile(desk)

    return render_template('helpdesk/maindesk.html',
                           desk=desk,
                           data=data,
                           reporter=reporter,
                           form=form,
                           calendar=agileCalendar)


@helpdesk.route("/channel/<channelname>", methods=['GET', 'POST'])
@login_required
def channel(channelname):
    refresh = request.args.get('refresh') if request.args.get('refresh') else False
    deskname = 'Main-Help-Desk'
    form = SelectForm()
    options = [(n,item) for n,item in enumerate(helpdeskBookByName[deskname].channels)]
    if request.method == 'POST':
        channelname = dict(options)[int(form.select.data)]
        return redirect(url_for('.channel', channelname=channelname))
    form.select.choices = options

    channel = helpdeskBookByName[deskname].channels[channelname]
    channeldata = ChannelDeck(channel, *Data.getChannel(channel.key))

    if channeldata.source == 'store':
        flash('Data from local storage obtained at {}'.format(channeldata.timestamp))

    if refresh:
        if channeldata.source == 'store':
            flash('Unable to get fresh data from JIRA server')
            reporter = ChannelReporter.fromFile(channel)
        else:
            reporter = ChannelReporter(channel, channeldata)
    else:
        reporter = ChannelReporter.fromFile(channel)

    return render_template('helpdesk/maindeskchannel.html',
                           book = helpdeskBookByName, helpdeskname = deskname, channelname=channelname,
                           data = channeldata,
                           reporter = reporter,
                           form = form,
                           calendar=agileCalendar)

@helpdesk.route("/lab")
#@login_required
def lab():
    deskname = 'Main-Help-Desk'
    channelname = 'Lab'
    channel = helpdeskBookByName[deskname].channels[channelname]
    channeldata = ChannelDeck(channel, *Data.getChannel(channel.key))
    if channeldata.source == 'store':
        flash('Data from local storage obtained at {}'.format(channeldata.timestamp))
    reporter = ChannelReporter.fromFile(channel)
    return render_template('helpdesk/pchannel.html',
                           book = helpdeskBookByName, helpdeskname = deskname, channelname=channelname,
                           data = channeldata,
                           reporter = reporter,
                           calendar=agileCalendar)

@helpdesk.route("/tech")
#@login_required
def tech():
    deskname = 'Main-Help-Desk'
    channelname = 'Tech'
    channel = helpdeskBookByName[deskname].channels[channelname]
    channeldata = ChannelDeck(channel, *Data.getChannel(channel.key))
    if channeldata.source == 'store':
        flash('Data from local storage obtained at {}'.format(channeldata.timestamp))
    reporter = ChannelReporter.fromFile(channel)

    return render_template('helpdesk/pchannel.html',
                           book = helpdeskBookByName, helpdeskname = deskname, channelname=channelname,
                           data = channeldata,
                           reporter = reporter,
                           calendar=agileCalendar)

@helpdesk.route("/coaches", methods=['GET', 'POST'])
@login_required
def coaches():
    refresh = request.args.get('refresh') if request.args.get('refresh') else False
    desk = helpdeskBookByName['Coaches-Help-Desk']

    form = SelectForm()
    options = [(n,item) for n,item in enumerate(desk.channels)]
    if request.method == 'POST':
        channelname = dict(options)[int(form.select.data)]
        return redirect(url_for('.cchannel', channelname=channelname))
    form.select.choices = options

    if refresh:
        data = Deck(*Data.getFocusedDesk(desk))
        if data.source == 'store':
            flash('Unable to get fresh data from JIRA server')
        else:
            reporter = DeskReporter(desk, data)
    else:
        data = Deck(*Data.getDesk(desk))
        if data.source == 'store':
            flash('Data from local storage obtained at {}'.format(data.timestamp))

    reporter = DeskReporter.fromFile(desk)

    return render_template('helpdesk/coachesdesk.html',
                           desk=desk,
                           form=form,
                           data=data,
                           reporter=reporter,
                           calendar=agileCalendar)

@helpdesk.route("/coaches/channel/<channelname>", methods=['GET', 'POST'])
@login_required
def cchannel(channelname):
    refresh = True if request.args.get('refresh') else False
    deskname = 'Coaches-Help-Desk'
    form = SelectForm()
    options = [(n,item) for n,item in enumerate(helpdeskBookByName[deskname].channels)]
    if request.method == 'POST':
        channelname = dict(options)[int(form.select.data)]
        return redirect(url_for('.cchannel', channelname=channelname))

    form.select.choices = options
    channel = helpdeskBookByName[deskname].channels[channelname]
    channeldata = ChannelDeck(channel, *Data.getChannel(channel.key))

    if channeldata.source == 'store':
        flash('Data from local storage obtained at {}'.format(channeldata.timestamp))

    if refresh:
        if channeldata.source == 'store':
            flash('Unable to get fresh data from JIRA server')
            reporter = ChannelReporter.fromFile(channel)
        else:
            reporter = ChannelReporter(channel, channeldata)
    else:
        reporter = ChannelReporter.fromFile(channel)

    return render_template('helpdesk/coachesdeskchannel.html',
                           book = helpdeskBookByName, helpdeskname = deskname, channelname=channelname,
                           data = channeldata,
                           reporter = reporter, form = form,
                           calendar=agileCalendar)


@helpdesk.route("/tools", methods=['GET', 'POST'])
@login_required
def tools():
    refresh = True if request.args.get('refresh') else False
    desk = helpdeskBookByName['ToolsSupport-Help-Desk']
    form = SelectForm()
    options = [(n,item) for n,item in enumerate(desk.channels)]
    if request.method == 'POST':
        channelname = dict(options)[int(form.select.data)]
        return redirect(url_for('.tchannel', channelname=channelname))
    form.select.choices = options

    if refresh:
        data = iDeck(*Data.getFocusedDesk(desk))
        if data.source == 'store':
            flash('Unable to get fresh data from JIRA server')
        else:
            reporter = DeskReporter(desk, data)
    else:
        data = iDeck(*Data.getDesk(desk))
        if data.source == 'store':
            flash('Data from local storage obtained at {}'.format(data.timestamp))

    reporter = DeskReporter.fromFile(desk)



    return render_template('helpdesk/toolsdesk.html',
                           desk=desk,
                           form=form,
                           data=data,
                           reporter=reporter,
                           calendar=agileCalendar)


@helpdesk.route("/tools/channel/<channelname>", methods=['GET', 'POST'])
@login_required
def tchannel(channelname):
    refresh = True if request.args.get('refresh') else False
    deskname = 'ToolsSupport-Help-Desk'
    form = SelectForm()
    options = [(n,item) for n,item in enumerate(helpdeskBookByName[deskname].channels)]
    if request.method == 'POST':
        channelname = dict(options)[int(form.select.data)]

app/templates/helpdesk/coachesdesk.html
{% extends "helpdesk/layout.html" %}
{% import 'helpdeskLib.html' as hd %}
{% import 'identificationLib.html' as idnt %}
{% block header %} Coaches Desk {% block topic %} - Overview {% endblock %}{% endblock %}

{% block content %}
    <section>
        {% call idnt.deskIdentifier(desk) %}
            <form method="POST" action="{{ url_for('.coaches') }}" align="left">
                {{ form.select }} <input type="submit" value="GO!!" style="width: 80px; height: 40px;" >
            </form>
        {% endcall %}
        <p style="text-align: center; margin-bottom: 0; margin-top: 0">COACHES HELP DESK - OVERALL STATISTICS</p>
        {% set stats = reporter.stats %}
        <p style="text-align: center; margin-bottom: 0; margin-top: 0">ALL: n = {{ stats.n }};
            {{ hd.displayStats(stats) }}
        </p>
        {% set stats = reporter.statsOfRecent %}
        <p style="text-align: center; margin-bottom: 0; margin-top: 0; color:green">CREATED IN LAST 60 DAYS: n = {{ stats.n }};
            {{ hd.displayStats(stats) }}
        </p>
        {% set stats = reporter.statsOfPending %}
        <p style="text-align: center; margin-bottom: 0; margin-top: 0; color:red">PENDING: n = {{ stats.n }};
            {{ hd.displayStats(stats) }}
        </p>
        <table class='desk_graphs'>
            <colgroup>
                <col class="column">
                <col class="column">
            </colgroup>

            <tbody>
            {{ hd.drawDeskChannels(reporter) }}
            {{ hd.drawMonthEvolution(data) }}

        </table>
            <p style="text-align: center; margin-bottom: 0; margin-top: 0">
                Graph computed with data collected at {{ data.timestamp }} <br>
            <a href="{{ url_for('helpdesk.coaches', refresh=True) }}"> Refresh Graphs</a>
        </p>
    </section>

    <section id="urgent">
        <table class='urgent_dashboard'>
        <colgroup>
            <col id="key">
            <col id="component">
            <col id="name">
            <col id="status">
            <col id="priority">
            <col id="age">
            <col id="assignee">
            <col id="links">
        </colgroup>
        <thead>
        <tr id='title'><th colspan="8">COACHES HELP DESK</th></tr>
        <tbody>

        <tr id="overdue"><th colspan="8">Unresolved Requests </th></tr>
        {% for issue in data.unresolved %}
            {% if loop.first %}
            <tr>
                <th>Key</th>
                <th>Channel</th>
                <th>Name</th>
                <th>Status</th>
                <th>Priority</th>
                <th> Age</th>
                <th>Assignee</th>
                <th>Links</th>
            </tr>
            {% endif %}
            <tr class="{{ loop.cycle('odd', 'even')}}">
                {{ hd.displayDeskIssue(issue) }}
            </tr>
            {% if loop.last %}
            <tr>
                <td colspan="8"> >>> {{loop.length }} items found</td>
            </tr>
            {% endif %}
        {% else %}
            <tr>
                <td colspan="8"> >>> No Issues found</td>
            </tr>
        {% endfor %}
        </table>

        <table class='urgent_dashboard'>
        <colgroup>
            <col id="resolved">
            <col id="key">
            <col id="name">
            <col id="status">
            <col id="resolution">
            <col id="priority">
            <col id="age">
            <col id="assignee">
            <col id="links">
        </colgroup>
        <tbody>
        <tr style="background-color: yellowgreen"><th colspan="9">Resolved Requests in last 60 days </th></tr>
        {% for issue in data.lastResolved %}
            {% if loop.first %}
            <tr>
                <th>Resolution Date</th>
                <th>Key</th>
                <th>Summary</th>
                <th>Status</th>
                <th>Resolution</th>
                <th>Priority</th>
                <th>Age</th>
                <th>Assignee</th>
                <th>Links</th>
            </tr>
            {% endif %}
            <tr class="{{ loop.cycle('odd', 'even')}}">
                {{ hd.displayResolvedIssue(issue) }}
            </tr>
            {% if loop.last %}
            <tr>
                <td colspan="7"> >>> {{loop.length }} items found</td>
            </tr>
            {% endif %}
        {% else %}
            <tr>
                <td colspan="7"> >>> No Issues found</td>
            </tr>
        {% endfor %}
        </table>


    </section>
{% endblock %}

app/templates/helpdesk/coachesdeskchannel.html
{% extends "helpdesk/layout.html" %}
{% import 'identificationLib.html' as idnt %}
{% import 'helpdeskLib.html' as hd %}
{% block header %} Coaches Desk {% block topic %} - {{ channelname }} Channel {% endblock %} {% endblock %}
{% block content %}
    {% set channel = book[helpdeskname].channels[channelname] %}

    <section>
    {% call idnt.channelIdentifier(book, helpdeskname, channelname) %}
        <form method="POST" action="{{ url_for('helpdesk.cchannel', channelname=channelname) }}" align="left">
            {{ form.select }} <input type="submit" value="GO!!" style="width: 80px; height: 40px;" >
        </form>
    {% endcall %}
    </section>

    <section>
    {% if reporter|length %}
        <p style="text-align: center; margin-bottom: 0; margin-top: 0"> OVERALL CHANNEL STATISTICS </p>
        {% set stats = reporter.stats %}
        <p style="text-align: center; margin-bottom: 0; margin-top: 0">ALL: n = {{ stats.n }};
            {{ hd.displayStats(stats) }}
        </p>
        {% set stats = reporter.statsOfRecent %}
        <p style="text-align: center; margin-bottom: 0; margin-top: 0; color:green">CREATED IN LAST 60 DAYS: n = {{ stats.n }};
            {{ hd.displayStats(stats) }}
        </p>
        {% set stats = reporter.statsOfPending %}
        <p style="text-align: center; margin-bottom: 0; margin-top: 0; color:red">PENDING: n = {{ stats.n }};
            {{ hd.displayStats(stats) }}
        </p>
        <table class='desk_graphs'>
            <colgroup>
                <col class="column">
                <col class="column">
            </colgroup>

            <tbody>
                {{ hd.drawEvolutionDesk(reporter) }}
                {{ hd.drawMonthEvolution(data) }}

        </table>
        <p style="text-align: center; margin-bottom: 0; margin-top: 0">
            Graph computed with data collected at {{ data.timestamp }} <br>
            <a href="{{ url_for('helpdesk.cchannel', channelname=channelname, refresh=True) }}"> Refresh Graphs</a>
        </p>
    {% endif %}
    </section>

    <section>
        <table class='help_board'>
        <colgroup>
            <col id="key">
            <col id="name">
            <col id="status">
            <col id="priority">
            <col id="age">
            <col id="assignee">
            <col id="links">
        </colgroup>
        <thead>
        <tr id='title'><th colspan="8">{{ channelname }} CHANNEL</th></tr>
        <tbody>
        <tr id="unresolved"><th colspan="8">Unresolved Requests </th></tr>

        {% for issue in data.unresolved %}
            {% if loop.first %}
            <tr>
                <th>Key</th><th>Summary</th><th>Status</th><th>Priority</th><th>Age</th><th>Assignee</th><th>Links</th>
            </tr>
            {% endif %}
            <tr class="{{ loop.cycle('odd', 'even')}}">
                {{ hd.displayChannelIssue(issue) }}
            </tr>
            {% if loop.last %}
            <tr>
                <td colspan="7"> >>> {{loop.length }} items found</td>
            </tr>
            {% endif %}
        {% else %}
            <tr>
                <td colspan="7"> >>> No Issues found</td>
            </tr>
        {% endfor %}
        </table>

        <table class='help_board'>
        <colgroup>
            <col id="resolved">
            <col id="key">
            <col id="name">
            <col id="status">
            <col id="priority">
            <col id="age">
            <col id="assignee">
            <col id="links">
        </colgroup>
        <tbody>
        <tr style="background-color: yellowgreen"><th colspan="8">Resolved Requests in last 60 days</th></tr>
        {% for issue in data.lastResolved %}
            {% if loop.first %}
            <tr>
                <th>Resolution Date</th>
                <th>Key</th>
                <th>Summary</th>
                <th>Status</th>
                <th>Priority</th>
                <th>Age</th>
                <th>Assignee</th>
                <th>Links</th>
            </tr>
            {% endif %}
            <tr class="{{ loop.cycle('odd', 'even')}}">
                {{ hd.displayResolvedIssue(issue) }}
            </tr>
            {% if loop.last %}
            <tr>
                <td colspan="7"> >>> {{loop.length }} items found</td>
            </tr>
            {% endif %}
        {% else %}
            <tr>
                <td colspan="7"> >>> No Issues found</td>
            </tr>
        {% endfor %}
        </table>
    </section>
{% endblock %}

app/templates/helpdesk/layout.html
{% extends "layout.html" %}
{% block tool %} Help Desk {% endblock %}
{% block header %} {% block topic %} {% endblock %} {% endblock %}

{% block submenu %}
     <nav  id="menu">
        <ul>
            <li><a href="{{ url_for('.main') }}" class="active">Main</a></li>
            <li><a href="{{ url_for('.lab') }}" class="active">M-Lab</a></li>
            <li><a href="{{ url_for('.tech') }}" class="active">M-Tech</a></li>
            <li><a href="{{ url_for('.coaches') }}" class="active">Coaches</a></li>
            <li><a href="{{ url_for('.tools') }}" class="active"> Tools Support</a></li>
        </ul>
    </nav>
    <!--
    <script>
        (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
                    (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
                m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
        })(window,document,'script','https://www.google-analytics.com/analytics.js','ga');
        ga('create', 'UA-80877512-3', 'auto');
        ga('send', 'pageview');
    </script>
    -->
{% endblock %}

app/templates/helpdesk/maindesk.html
{% extends "helpdesk/layout.html" %}
{% import 'helpdeskLib.html' as hd %}
{% import 'identificationLib.html' as idnt %}
{% block header %} Main Desk {% block topic %} - Unresolved Requests{% endblock %}{% endblock %}

{% block content %}
    <section>
        {% call idnt.deskIdentifier(desk) %}
            <form method="POST" action="{{ url_for('.main') }}" align="left">
                {{ form.select }} <input type="submit" value="GO!!" style="width: 80px; height: 40px;" >
            </form>
        {% endcall %}

        <p style="text-align: center; margin-bottom: 0; margin-top: 0">MAIN HELP DESK - OVERALL STATISTICS</p>
        {% set stats = reporter.stats %}
        <p style="text-align: center; margin-bottom: 0; margin-top: 0">ALL: n = {{ stats.n }};
            {{ hd.displayStats(stats) }}
        </p>
        {% set stats = reporter.statsOfRecent %}
        <p style="text-align: center; margin-bottom: 0; margin-top: 0; color:green">CREATED IN LAST 60 DAYS: n = {{ stats.n }};
            {{ hd.displayStats(stats) }}
        </p>
        {% set stats = reporter.statsOfPending %}
        <p style="text-align: center; margin-bottom: 0; margin-top: 0; color:red">PENDING: n = {{ stats.n }};
            {{ hd.displayStats(stats) }}
        </p>

        <table class='desk_graphs'>
            <colgroup>
                <col class="column">
                <col class="column">
            </colgroup>

            <tbody>
            {{ hd.drawDeskChannels(reporter) }}
            {{ hd.drawMonthEvolution(data) }}

        </table>
        <p style="text-align: center; margin-bottom: 0; margin-top: 0">
            Graphs computed with data collected at {{ data.timestamp }} <br>
            <a href="{{ url_for('helpdesk.main', refresh=True) }}"> Refresh Graph</a>
        </p>
    </section>
    <section id="urgent">
        <table class='urgent_dashboard'>
        <colgroup>
            <col id="key">
            <col id="channel">
            <col id="summary">
            <col id="status">
            <col id="priority">
            <col id="age">
            <col id="assignee">
            <col id="links">
        </colgroup>
        <thead>
        <tr id='title'><th colspan="8">MAIN HELP DESK</th></tr>
        <tbody>

        <tr id="overdue"><th colspan="8">Unresolved Requests </th></tr>
        {% for issue in data.unresolved %}
            {% if loop.first %}
            <tr>
                <th>Key</th>
                <th>Channel</th>
                <th>Summary</th>
                <th>Status</th>
                <th>Priority</th>
                <th>Age</th>
                <th>Assignee</th>
                <th>Links</th>
            </tr>
            {% endif %}
            <tr class="{{ loop.cycle('odd', 'even')}}">
                {{ hd.displayDeskIssue(issue) }}
            </tr>
            {% if loop.last %}
            <tr>
                <td colspan="8"> >>> {{loop.length }} items found</td>
            </tr>
            {% endif %}
        {% else %}
            <tr>
                <td colspan="8"> >>> No Issues found</td>
            </tr>
        {% endfor %}
        </table>

        <table class='urgent_dashboard'>
        <colgroup>
            <col id="resolved">
            <col id="key">
            <col id="name">
            <col id="status">
            <col id="resolution">
            <col id="priority">
            <col id="age">
            <col id="assignee">
            <col id="links">
        </colgroup>
        <tbody>
        <tr style="background-color: yellowgreen"><th colspan="9">Resolved Requests in last 60 days </th></tr>
        {% for issue in data.lastResolved %}
            {% if loop.first %}
            <tr>
                <th>Resolution Date</th>
                <th>Key</th>
                <th>Summary</th>
                <th>Status</th>
                <th>Resolution</th>
                <th>Priority</th>
                <th>Age</th>
                <th>Assignee</th>
                <th>Links</th>
            </tr>
            {% endif %}
            <tr class="{{ loop.cycle('odd', 'even')}}">
                {{ hd.displayResolvedIssue(issue) }}
            </tr>
            {% if loop.last %}
            <tr>
                <td colspan="7"> >>> {{loop.length }} items found</td>
            </tr>
            {% endif %}
        {% else %}
            <tr>
                <td colspan="7"> >>> No Issues found</td>
            </tr>
        {% endfor %}
        </table>

    </section>
{% endblock %}

app/templates/helpdesk/overview.html
{% extends "helpdesk/layout.html" %}
{% import 'helpdeskLib.html' as hd %}
{% import 'identificationLib.html' as idnt %}
{% block header %} Main Desk {% block topic %} - Overview {% endblock %} {% endblock %}


{% block content %}
    <section>
        {% set desk = maindesk %}
        {% set reporter = mainreporter %}

        {% call idnt.deskOverviewIdentifier(desk) %}
            {{ url_for('helpdesk.main') }}
        {% endcall %}
        <p style="text-align: center; margin-bottom: 0; margin-top: 0"> MAIN HELP DESK - OVERALL STATISTICS </p>
        {% set stats = reporter.stats %}
        <p style="text-align: center; margin-bottom: 0; margin-top: 0"> ALL: n = {{ stats.n }};
            {{ hd.displayStats(stats) }}
        </p>
        {% set stats = reporter.statsOfRecent %}
        <p style="text-align: center; margin-bottom: 0; margin-top: 0; color:green">CREATED IN LAST 60 DAYS: n = {{ stats.n }};
            {{ hd.displayStats(stats) }}
        </p>
        {% set stats = reporter.statsOfPending %}
        <p style="text-align: center; margin-bottom: 0; margin-top: 0; color:red">PENDING: n = {{ stats.n }};
            {{ hd.displayStats(stats) }}
        </p>

        <table class='desk_graphs'>
            <colgroup>
                <col class="column">
                <col class="column">
            </colgroup>

            <tbody>
            {{ hd.drawEvolutionNDesk('0', reporter) }}
            {{ hd.drawChannelsNDesk('0',reporter) }}

        </table>
    </section>
    <section>
        {% set desk = coachdesk %}
        {% set reporter = coachreporter %}

        {% call idnt.deskOverviewIdentifier(desk) %}
            {{ url_for('helpdesk.coaches') }}
        {% endcall %}

        <p style="text-align: center; margin-bottom: 0; margin-top: 0"> COACHES HELP DESK - OVERALL STATISTICS </p>
        {% set stats = reporter.stats %}
        <p style="text-align: center; margin-bottom: 0; margin-top: 0">ALL: n = {{ stats.n }};
            {{ hd.displayStats(stats) }}
        </p>
        {% set stats = reporter.statsOfRecent %}
        <p style="text-align: center; margin-bottom: 0; margin-top: 0; color:green"> CREATED IN LAST 60 DAYS: n = {{ stats.n }};
            {{ hd.displayStats(stats) }}
        </p>
        {% set stats = reporter.statsOfPending %}
        <p style="text-align: center; margin-bottom: 0; margin-top: 0; color:red">PENDING: n = {{ stats.n }};
            {{ hd.displayStats(stats) }}
        </p>

        <table class='desk_graphs'>
            <colgroup>
                <col class="column">
                <col class="column">
            </colgroup>

            <tbody>
            {{ hd.drawEvolutionNDesk('1', reporter) }}
            {{ hd.drawChannelsNDesk('1',reporter) }}

        </table>
    </section>

{% endblock %}